name: Formatting tests

on:
  pull_request:
    branches:
      - main

jobs:
  formatting_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/ci-setup
        with:
          python-version: 3.10

      - name: Run black
        run: poetry run black --check .
        
      - name: Run isort
        run: poetry run isort --check-only .